# LEMP server provisioning for DigitalOcean.
#
# @author 1nfinitum (Mykhaylo Kolesnik) (2017).

---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/defaults.yml
    - vars/vars.yml
  vars_prompt:
    - name: "server_status"
      prompt: "Should server be 'present' or 'absent'?"
      default: "present"
      private: no

  tasks:

    - name: Adding SSH key for authentication.
      digital_ocean:
        command: ssh
        api_token: "{{ api_token | default('') }}"
        state: present
        name: "{{ droplet_name }}"
        ssh_pub_key: "{{ lookup('file', '{{ public_ssh_key_root }}') }}"
      register: ssh_key

    - name: Creating/deleting droplet.
      digital_ocean:
        api_token: "{{ api_token | default('') }}"
        state: "{{ server_status }}"
        command: droplet
        name: "{{ droplet_name }}"
        private_networking: yes
        image_id: "{{ distro }}"
        size_id: 512mb
        region_id: fra1
        ssh_key_ids: "{{ ssh_key.ssh_key.id }}"
        unique_name: yes
      register: do

    - debug: var=do
    - name: Choose right ansible python interpreter in case of Centos6
      set_fact: python=/usr/bin/python
      when: distro == "centos-6-x32"

    - name: Check if machine was already created to choose the right user for provisioning.
      set_fact: provisioning_user=deploy ansible_become=true python=/usr/bin/python
      when: do.changed == false

    - wait_for:
        port: 22
        host: "{{ do.droplet.ip_address }}"
      when: do.droplet is defined and server_status != "absent" and do.changed == true

    - name: Adding DNS record in DigitalOcean.
      digital_ocean_domain:
        api_token: "{{ api_token | default('') }}" 
        name: "{{ domain_name }}"
        state: "{{ server_status }}"
        ip: "{{ do.droplet.ip_address }}"
      when: domain_name is defined and do.changed == true and server_status != "absent"

    - name: Deleting DNS record from DigitalOcean.
      digital_ocean_domain:
        api_token: "{{ api_token | default('') }}" 
        name: "{{ domain_name }}"
        state: "{{ server_status }}"
      when: domain_name is defined and server_status == "absent"

    - name: Retrieve host ip
      ipify_facts:

    - name: Add new host to our inventory.
      add_host:
        name: "{{ do.droplet.ip_address }}"
        groups: do
        ansible_python_interpreter: "{{ python | default('/usr/bin/python3') }}"
        ansible_user: "{{ provisioning_user | default('root') }}"
        ansible_become: "{{ ansible_become | default('') }}"
        ansible_become_pass: "deploy"
        ansible_ssh_private_key_file: "{{ private_ssh_key_root }}"
        user_pass: "{{ user_pass }}"
        mysql_ip: "{{ ipify_public_ip }}"
        ansible_port: "{{ security_ssh_port }}"
      when: do.droplet is defined and server_status != "absent"
      changed_when: false

- hosts: do
  gather_facts: true

  vars_files:
    - vars/defaults.yml
    - vars/vars.yml

  pre_tasks:
      - name: Add 'deploy' group
        group: 
          name: deploy
          state: present

      - name: Add user 'deploy'
        user: 
            name: deploy
            state: present
            createhome: yes
            shell: /bin/bash
            group: deploy
            password: "{{ user_pass }}"

      - name: Add ssh-authentication key for deploy
        authorized_key: 
            key: "{{ lookup('file', '{{ public_ssh_key_root }}') }}"
            user: deploy
            state: present

      - name: Set Ansible to use private key for connection, that corresponds `public_ssh_root`.
        set_fact: ansible_ssh_private_key_file={{ private_ssh_key_root }}

      - name: Set Centos6 required variables
        set_fact: mysql_enablerepo=remi php_enablerepo=remi
        when: ansible_os_family == "RedHat"

      - name: Include Centos6 Remi repo role if needed
        include_role:
            name: geerlingguy.repo-remi
        when: ansible_os_family == "RedHat"

      - name: Include Centos6 Epel repo role if needed
        include_role:
            name: geerlingguy.repo-epel        
        when: ansible_os_family == "RedHat"

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - role: geerlingguy.mysql
      ansible_python_interpreter: "/usr/bin/python"
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.composer
