---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create new Droplet.
      digital_ocean:
        state: present
        command: droplet
        name: ansible-do
        private_networking: yes
        image_id: ubuntu-16-04-x32
        size_id: 512mb
        region_id: fra1
        ssh_key_ids: 6743524
        unique_name: yes
      register: do

    - name: Check if machine was already created to choose the right user for provisioning.
      set_fact: provisioning_user="deploy", ansible_become=true
      when: do.changed == false

    - name: Add new host to our inventory.
      add_host:
        name: "{{ do.droplet.ip_address }}"
        groups: do
        ansible_python_interpreter: "/usr/bin/python3"
        ansible_user: "{{ provisioning_user | default('root') }}"
        ansible_become: "{{ ansible_become | default('false') }}"
        ansible_become_pass: "deploy"
      when: do.droplet is defined
      changed_when: false

- hosts: do
  remote_user: "{{ ansible_user }}"
  gather_facts: true

  vars_files:
    - vars/main.yml

  pre_tasks:

      - name: Add 'deploy' group
        group: 
          name: deploy
          state: present

      - name: Add user 'deploy'
        user: 
            name: deploy
            state: present
            createhome: yes
            shell: /bin/bash
            group: deploy
            password: $6$rounds=656000$49G.PQKkbGk2ngY1$BUDsC3aQf3XXPpsU8.JPP94URmiYF21fbYdxU/K8G0iJstvc3EEVmrFW5K51b7q4J.qgliRV16O5tpMSjuXhY1

      - name: Add ssh-authentication key for deploy
        authorized_key: 
            key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
            user: deploy
            state: present

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.composer
