---
# LEMP server provisioning.
#
# @author 1nfinitum (Mykhaylo Kolesnik) (2017).

- hosts: lemp
  gather_facts: true

  vars_files:
    - vars/defaults.yml
    - vars/vars.yml

  vars:
      - mysql_ip: 192.168.33.1 


  pre_tasks:

      - name: Add 'deploy' group
        group: 
          name: deploy
          state: present

      - name: Add user 'deploy'
        user: 
            name: deploy
            state: present
            createhome: yes
            shell: /bin/bash
            group: deploy
            password: "{{ user_pass }}"

      - name: Add ssh-authentication key for deploy
        authorized_key: 
            key: "{{ lookup('file', '{{ public_ssh_key_root }}') }}"
            user: deploy
            state: present

      - name: Set Ansible to use private key for connection, that corresponds `public_ssh_root`.
        set_fact: ansible_ssh_private_key_file={{ private_ssh_key_root }}

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - role: geerlingguy.mysql
      become: yes
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.composer
